### ISSUE TITLE
In case of 'Order quantity exceeded upper limit' Bybit erroneously reloads

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#139]
The proper behavior: just display the error saving the information to the filelog.log.

2024-04-17 20:14:13,939 - api.bybit.errors - ERROR - InvalidRequestError - Order quantity exceeded upper limit. (ErrCode: 170135) (ErrTime: 17:14:13).
Request → POST https://api-testnet.bybit.com/v5/order/create: {"category": "spot", "symbol": "BTCUSDT", "side": "Sell", "orderType": "Limit", "qty": "1000000.0", "price": "62000.00", "orderLinkId": "1223648070.BTCUSDT.spot"}.

**Comment by evgrmn** [comment]
I processed this error in the file api/bybit/errors.py and it ends up in the log. The maxOrderQty field is currently empty. Technically, it’s not a problem to add it when loading instruments data, so as not to send inconsistent requests in the future but cut them off earlier.

**Comment by nikolayromenskiy** [comment]
This error like any other must appear on the screen in the info widget, not only in the logfile.
