### ISSUE TITLE
After 'Insufficient available balance' for Bybit and for Bitmex 'Invalid orderQty (400 else)'

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#140]
1. The exchange button turns red. This is wrong. The proper behavior: turn the trading off, but the exchange status must be normal.
2. When I try again to invoke 'Insufficient available balance' (or 'Invalid orderQty' for Bitmex) putting a new order, the error does not appear on the screen, appearing only in the terminal and in the logfile.log.

**Comment by evgrmn** [comment]
After the correction, the behavior is as follows: 1) Exchange status is ONLINE, 2) Automatic trading is disabled, 3) logNumFatal = 0, 4) The error message appears both in the “Information” widget and in the log file as many times as the error occurs.
