### ISSUE TITLE
Switching between the exchanges

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#141]
Tmatic must remember the last instrument's choice (yellow line) for each market. What I see now: the instrument's choice resets to the first position and the 'yellow line' lives its own life, sometimes I see two lines simultaneously (look at the screenshot below).

![Screenshot from 2024-04-17 20-41-33](https://github.com/evgrmn/tmatic/assets/148801289/e6a6115b-c1c9-4d3e-904d-4bec8a260b4c)

**Comment by evgrmn** [comment]
Solved: handler_position("event", row_position=Tables.position.mod) in clear_tables() after shifting markets.
