### ISSUE TITLE
Wrong behavior. When I click the first row in the orders' table, the third one is chosen

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#144]
When I click the second row, the first one is chosen
When I click the third row, the second one is chosen
The screenshot below depicts the situation when I clicked the first row.

![Screenshot from 2024-04-18 09-35-22](https://github.com/evgrmn/tmatic/assets/148801289/23cd77d0-4d49-495e-8422-c17b317f4614)

**Comment by evgrmn** [comment]
Fixed by adding column sorting for the orders object in the ListBoxTable class.
