### ISSUE TITLE
Commission fees getting to the database have some random values

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#156]

**Comment by evgrmn** [comment]
There may have been some confusion during debugging. You should rewrite the database. The newly rewritten database looks like below. The last column “Commission Rate” is calculated based on the database values.

EXECID|MARKET|SYMBOL|CATEGORY|CURRENCY|SIDE|QTY|PRICE|COMMISS|rate=COMMISS/PRICE*QTY|
|---|---|---|---|---|---|---|---|---|---|
4c372468-57a5-5cbc-9b1d-f3bc31f732d5|Bybit|BTCUSDT|linear|USDT|0|0.001|64207.4|0.03531407|0.00055
c991722b-bb37-58c0-8f63-df103beb04c8|Bybit|BTCUSDT|linear|USDT|1|0.001|64190.1|0.035304555|0.00055
a8dcf027-0a4b-5e2d-ab49-cec898efab66|Bybit|BTCUSDT|linear|USDT|1|0.001|64152.1|0.035283655|0.00055
b03345ec-47e8-58f1-8499-6a6c0821abac|Bybit|BTCUSDT|linear|USDT|0|0.001|64116|0.0352638|0.00055
240b17d7-5ad9-519d-af83-443861589adb|Bybit|BTCUSDT|linear|USDT|0|0.001|61869.1|0.034028005|0.00055
24567684-c638-577d-ab35-9426873a317a|Bybit|BTCUSDT|linear|USDT|1|0.001|61878|0.0340329|0.00055
bdf3a0b5-e433-5117-888e-a8234cad2f01|Bybit|BTCUSDT|linear|USDT|1|0.001|61967.6|0.03408218|0.00055
b873bd6c-d4cd-5a60-94b2-8f7cc8e1a9d8|Bybit|BTCUSDT|linear|USDT|0|0.001|61811|0.03399605|0.00055
c7fbfb5c-27bd-5fee-b161-b22f69282cbb|Bybit|BTCUSDT|linear|USDT|1|0.009|62125.3|0.307520235|0.00055
95589d95-a4da-5bec-a36b-b9eda0a40d23|Bybit|BTCUSDT|linear|USDT|1|0.001|62162|0.0341891|0.00055
015662a8-780c-5a85-afa3-86273f647cc9|Bybit|BTCUSDT|linear|USDT|0|0.01|62175.1|0.34196305|0.00055
059b602f-a776-5354-8cd2-266753646aca|Bybit|BTCUSDT|linear|USDT|0|0.04|62344.7|1.3715834|0.00055
28130f54-36ad-5158-83ba-c61b6de19bbb|Bybit|BTCUSDT|linear|USDT|1|0.04|62414|1.373108|0.00055
28130f54-36ad-5158-83ba-c61b6de19bbb|Bybit|BTCUSDT|linear|USDT|1|0.04|62414|1.373108|0.00055
3d846201-a017-5d7e-a338-a55f0450b602|Bybit|BTCUSDT|linear|USDT|1|0.04|62350|0.4988|0.0002
46008347-5821-5bf2-8911-c3a1e298eb20|Bybit|BTCUSDT|linear|USDT|1|0.001|62350|0.01247|0.0002
69e972f3-0b01-5472-9459-d9d00c8aeea8|Bybit|BTCUSDT|linear|USDT|1|0.009|62350|0.11223|0.0002
f947bb24-90ee-5313-a45f-fdf102174644|Bybit|BTCUSDT|linear|USDT|0|0.05|62278.6|1.7126615|0.00055
02100000000071500000|Bybit|BTCUSDT|spot|None|0|0.01|55923.82|0.5592382|0.001
4a02c879-cc82-5c60-8ada-788fba3eb725|Bybit|BTCUSDT|linear|USDT|0|0.001|63395.5|0.034867525|0.00055
df1df631-5b6e-5047-8eb9-c45018f722d0|Bybit|BTCUSDT|linear|USDT|1|0.002|63317.3|0.06964903|0.00055
15356d76-30e7-5eb1-b9ff-dad4d141aa29|Bybit|BTCUSDT|linear|USDT|0|0.002|63375.3|0.06971283|0.00055
baf60fd5-5889-5b49-b4f4-0a4a89f5e4ee|Bybit|BTCUSDT|linear|USDT|1|0.001|63319.1|0.034825505|0.00055
3eef09df-3878-5b37-bb96-95e4e5cb0a41|Bybit|BTCUSDT|linear|USDT|0|0.05|62311|1.7135525|0.00055
02100000000071440000|Bybit|BTCUSDT|spot|None|0|0.000526|52248.01|0.02748245326|0.001
02100000000071440000|Bybit|BTCUSDT|spot|None|0|0.015312|52248.01|0.80002152912|0.001
02100000000071440000|Bybit|BTCUSDT|spot|None|0|0.015274|52248.01|0.79803610474|0.001
c920774b-bb52-5af5-9bdd-1f2b0366dc3a|Bybit|BTCUSDT|linear|USDT|1|0.031|62895.1|0.38994962|0.0002
e8e2fbad-b08e-522c-9357-4e9e455e9796|Bybit|BTCUSDT|linear|USDT|1|0.019|62895.1|0.23900138|0.0002
64f8e8db-1be0-5038-8b7e-3e4076df096f|Bybit|BTCUSDT|linear|USDT|0|0.05|62830|0.6283|0.0002
02100000000071430000|Bybit|BTCUSDT|spot|None|0|0.0001|50000|0.005|0.001
02100000000071430000|Bybit|BTCUSDT|spot|None|1|0.05|61242.11|3.0621055|0.001
02100000000071410000|Bybit|BTCUSDT|spot|None|0|0.018654|61242.07|1.14240957378|0.001
02100000000071410000|Bybit|BTCUSDT|spot|None|0|0.016689|61242.09|1.02206924001|0.001
02100000000071410000|Bybit|BTCUSDT|spot|None|0|0.014657|61242.11|0.89762560627|0.001
02100000000071350000|Bybit|BTCUSDT|spot|None|1|0.05|62762|3.1381|0.001
02100000000071350000|Bybit|BTCUSDT|spot|None|1|0.05|62200|3.11|0.001
4627fea8-8e7a-51bb-a3dd-e1010125a7fa|Bybit|BTCUSDT|linear|USDT|1|0.05|62325.1|1.71394025|0.00055
02100000000071330000|Bybit|BTCUSDT|spot|None|0|0.05|62761.2|3.13806|0.001
02100000000071330000|Bybit|BTCUSDT|spot|None|1|0.005387|62763.21|0.33810541227|0.001
02100000000071330000|Bybit|BTCUSDT|spot|None|1|0.00956|62763.21|0.6000162876|0.001
02100000000071330000|Bybit|BTCUSDT|spot|None|1|0.00956|62763.21|0.6000162876|0.001
02100000000071330000|Bybit|BTCUSDT|spot|None|1|0.01195|62763.21|0.7500203595|0.001
02100000000071330000|Bybit|BTCUSDT|spot|None|1|0.013543|62763.21|0.85000215303|0.001
02100000000071330000|Bybit|BTCUSDT|spot|None|1|0.000048|62761.24|0.00301253952|0.001
fc9be015-b864-5bf8-9bb2-70b3e2452b15|Bybit|BTCUSDT|linear|USDT|1|0.001|64240|0.012848|0.0002
02100000000071250000|Bybit|BTCUSDT|spot|None|1|0.0002|60020.22|0.012004044|0.001
02100000000071210000|Bybit|BTCUSDT|spot|None|0|0.0001|41000|0.0041|0.001
02100000000071200000|Bybit|BTCUSDT|spot|None|1|0.0001|54300|0.00543|0.001
02100000000071180000|Bybit|BTCUSDT|spot|None|1|0.0001|44000|0.0044|0.001
02100000000071170000|Bybit|BTCUSDT|spot|None|0|0.0001|40986|0.0040986|0.001
02100000000071170000|Bybit|BTCUSDT|spot|None|0|0.0001|42629.36|0.004262936|0.001
02100000000071170000|Bybit|BTCUSDT|spot|None|0|0.0001|42154.08|0.004215408|0.001
02100000000071170000|Bybit|BTCUSDT|spot|None|0|0.0001|42941.16|0.004294116|0.001
02100000000071160000|Bybit|BTCUSDT|spot|None|0|0.000050|46450|0.0023225|0.001
7d1cc34e-d31c-5807-ba3a-b3cd6574ecd1|Bybit|BTCUSDT|linear|USDT|0|0.001|62670|0.012534|0.0002
02100000000071160000|Bybit|BTCUSDT|spot|None|0|0.000050|51630.76|0.002581538|0.001
02100000000071130000|Bybit|BTCUSDT|spot|None|1|0.000050|63000|0.00315|0.001
02100000000071130000|Bybit|BTCUSDT|spot|None|1|0.000050|62001.29|0.0031000645|0.001
02100000000071010000|Bybit|BTCUSDT|spot|None|1|0.0005|58690|0.029345|0.001
02100000000071010000|Bybit|BTCUSDT|spot|None|0|0.001|58687.96|0.05868796|0.001
7d423b26-4bd9-52e7-a50f-118d315e7a8f|Bybit|BTCUSDT|linear|USDT|0|0.001|65985|0.013197|0.0002
57920de5-a649-55e5-92a4-6d96534375ba|Bybit|BTCUSDT|linear|USDT|1|0.001|66800|0.01336|0.0002
ff811eba-8657-5151-85d5-67d59c14e4a9|Bybit|BTCUSDT|linear|USDT|1|0.001|70720|0.014144|0.0002
2c515415-5748-5129-9851-3888b153ce1c|Bybit|BTCUSDT|linear|USDT|1|0.001|70690|0.014138|0.0002
ad72b85f-1cf0-5342-8069-3a8cc02c71c1|Bybit|BTCUSDT|linear|USDT|1|0.001|69400|0.01388|0.0002
25204777-5375-55e1-95f0-661c80c85a1f|Bybit|BTCUSDT|linear|USDT|0|0.001|68650|0.01373|0.0002
e19342dd-cb2e-5724-991e-60c3e712d7d1|Bybit|BTCUSDT|linear|USDT|1|0.001|68950|0.01379|0.0002
06b283bb-447a-59e7-9615-1b833eddc862|Bybit|BTCUSDT|linear|USDT|1|0.001|68810|0.013762|0.0002
2c013169-3c3c-51f8-bd73-02eee1ea63c5|Bybit|BTCUSDT|linear|USDT|0|0.001|68750|0.01375|0.0002
7c6278e0-cd80-5dbf-b38a-51f36b6e35b8|Bybit|BTCUSDT|linear|USDT|0|0.001|68920|0.013784|0.0002
01cd21ad-9521-5cd8-84be-162e84e76f92|Bybit|BTCUSDT|linear|USDT|1|0.001|69080|0.013816|0.0002
37c60107-94f7-5717-901b-a5e6708a4846|Bybit|BTCUSDT|linear|USDT|1|0.001|69060|0.013812|0.0002
388cc275-a89a-5008-9411-86a8ac0c1512|Bybit|BTCUSDT|linear|USDT|0|0.001|68950|0.01379|0.0002
30c25de1-5916-5d1a-bdb1-b1a1aac86320|Bybit|BTCUSDT|linear|USDT|0|0.001|69050|0.01381|0.0002
ea7b9898-6e4b-5192-aa91-32d33e48638b|Bybit|BTCUSDT|linear|USDT|1|0.001|69090|0.013818|0.0002
86703cf4-78a2-5e40-8111-27fc21601449|Bybit|BTCUSDT|linear|USDT|0|0.001|69030|0.013806|0.0002
baeba688-4db7-503a-8857-ea63c2c0e1b1|Bybit|BTCUSDT|linear|USDT|1|0.001|69045|0.013809|0.0002
9d8c436e-0946-5b23-a3ce-6712fc5a8c7d|Bybit|BTCUSDT|linear|USDT|1|0.001|69045|0.013809|0.0002
0be87b57-322f-5a98-a7f5-c9989297952d|Bybit|BTCUSDT|linear|USDT|0|0.001|68963.9|0.037930145|0.00055
833e6145-3f11-5a85-adc7-fe6cb5cf68ee|Bybit|BTCUSDT|linear|USDT|0|0.001|69122|0.0138244|0.0002
0d03d3df-18ff-5aae-ab24-f75710ea912c|Bybit|BTCUSDT|linear|USDT|0|0.001|69335|0.013867|0.0002
7ca346c0-75d2-530e-931e-7ee5f765d50d|Bybit|BTCUSDT|linear|USDT|1|0.001|69000.1|0.01380002|0.0002
692dcd38-2a89-5581-8265-6c4e1a1ed5e4|Bybit|BTCUSDT|linear|USDT|0|0.001|68960|0.013792|0.0002
6861271a-bcdf-59b1-bbf4-10195a2780e4|Bybit|BTCUSDT|linear|USDT|0|0.001|70501|0.0141002|0.0002
48b01f46-d64c-5cf0-b704-bd8379f5b8f7|Bybit|BTCUSDT|linear|USDT|1|0.003|71999.9|0.04319994|0.0002
c01986b0-b9f6-59f5-b50e-5ba9b2ec5040|Bybit|BTCUSDT|linear|USDT|0|0.003|71958.5|0.0431751|0.0002
e7d9dc8c-911b-5547-8caa-83bd69e80267|Bybit|BTCUSDT|linear|USDT|1|0.001|72380|0.014476|0.0002
2c3dcb93-ecc8-55dd-879c-b84d132f59de|Bybit|BTCUSDT|linear|USDT|1|0.001|72300|0.01446|0.0002
0f570571-7280-5f93-8b8e-a72be32484f2|Bybit|BTCUSDT|linear|USDT|0|0.001|72250|0.01445|0.0002
dbabb0c3-1af9-5a67-a512-40e854711b61|Bybit|BTCUSDT|linear|USDT|1|0.001|72282.8|0.03975554|0.00055
aa23729f-7909-5056-a4e2-0e13abd507df|Bybit|BTCUSDT|linear|USDT|0|0.001|72250|0.01445|0.0002
397ca1f4-dd04-56e0-ad9c-6f1bded259d4|Bybit|BTCUSDT|linear|USDT|0|0.001|72340|0.014468|0.0002
3b4e10ec-1f79-55c3-973f-6bc1710eec84|Bybit|BTCUSDT|linear|USDT|0|0.001|72410|0.014482|0.0002
c2706436-0b58-592f-81ce-abe70deb643f|Bybit|BTCUSDT|linear|USDT|1|0.001|72480|0.014496|0.0002
e54a7f33-5b5d-566c-be5b-5a9200e2e261|Bybit|BTCUSDT|linear|USDT|1|0.001|72350|0.01447|0.0002
86e5c38c-b9b3-59b1-b66d-cea2959939b7|Bybit|BTCUSDT|linear|USDT|1|0.001|72350|0.01447|0.0002
a6b59950-b654-58b1-973e-fd23943fb0f3|Bybit|BTCUSDT|linear|USDT|0|0.001|72250|0.01445|0.0002
e2afc79b-1649-5dcb-926f-ba84925e2631|Bybit|BTCUSDT|linear|USDT|0|0.001|72300|0.01446|0.0002
c1e5dc82-03d3-5520-968b-36d304d3636e|Bybit|BTCUSDT|linear|USDT|1|0.001|72550|0.01451|0.0002
f1175a69-54bd-539b-aa6d-6c28d92db4dd|Bybit|BTCUSDT|linear|USDT|0|0.001|70180|0.038599|0.00055
0ad83310-29d3-5eca-8e80-56a45f7a7dd8|Bybit|BTCUSDT|linear|USDT|1|0.001|77000|0.0154|0.0002
4ddbeb86-10b5-5271-a292-6a646b686f8c|Bybit|BTCUSDT|linear|USDT|0|0.001|69100|0.01382|0.0002
1105b3ea-23c2-5840-ac99-62365cca7f4e|Bybit|BTCUSDT|linear|USDT|1|0.001|70000|0.014|0.0002
a04f4b1a-87d9-5ce1-bab0-72ed3a2ce99d|Bybit|BTCUSDT|linear|USDT|1|0.001|69900|0.01398|0.0002
5d10c7a1-28e0-514c-8534-5134518d0a71|Bybit|BTCUSDT|linear|USDT|0|0.001|69477.9|0.038212845|0.00055
ab3c26f2-b1ba-54fb-95d4-49228bae7ccb|Bybit|BTCUSDT|linear|USDT|0|0.001|69830.6|0.03840683|0.00055

**Comment by nikolayromenskiy** [comment]
Try to make trades manually. Wrong values probably comes at that time.

**Comment by evgrmn** [comment]
You are right. Data received from websocket contains key "execFee" instead of "feeRate", fixed.
