### ISSUE TITLE
The red STATUS color

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#171]
According to readme description the red STATUS color is the status with unclosed positions. The NOT DEFINED status wrongly colored in red even when balance = 0.

**Comment by evgrmn** [comment]
According to the description "NOT DEFINED - when loading the program, a bot with a position not equal to zero **or active orders was found**". Check your orders in the order table.

**Comment by nikolayromenskiy** [comment]
I do realize about the active orders. But if the balance is 0, then the color should be black, not red like now.

**Comment by evgrmn** [comment]
Corrected README.md: Red STATUS color is for OFF, NOT DEFINED, NOT IN LIST and for RESERVED with unclosed positions.
