### ISSUE TITLE
The data does not appear after posting a new order

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#172]
I have posted a new order (see the screenshot), but no reaction from the termnal. After reloading (i.g. pressing F3) the order finally showed up in the orders' table.

![Screenshot from 2024-04-25 08-31-30](https://github.com/evgrmn/tmatic/assets/148801289/4af7630a-3e66-4322-8da4-f273ece966d8)

**Comment by evgrmn** [comment]
I haven't encountered such an error yet. The error is implicit. This is probably an exceptional case.

**Comment by evgrmn** [comment]
I looked at the screenshot again. An error occurred while connecting via websocket. You did not receive a response to your new order because the ws execution stream was disabled.
