### ISSUE TITLE
Posting a new order: lack of info

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#173]
Now it looks like "Posting side=Sell price=67305.5 qty=100.0". The information in the logfile (as well as in the terminal) should be more complete while manually posting a new order. EMI and Market names must be in the posting row.

**Comment by evgrmn** [comment]
Added information to the logger. The message looks like this "Posting symbol=('XBTUSDT', 'linear', 'Bitmex') clOrdID=1230356630.XBTUSDT.linear side=Sell price=71000.0 qty=-1000.0"
