### ISSUE TITLE
Bitmex Instrument's table: ENTRY, PNL, MCALL

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#177]
![Screenshot from 2024-04-26 14-05-18](https://github.com/evgrmn/tmatic/assets/148801289/24f1d020-a220-41d7-a276-88f975987b52)

1) No ENTRY for XBTUSDT position.
2) PNL seems to show the correct value, but in some wrong dimension comparing with UNRLZD_PNL in Money's table.
3) For XBTUSDT contract the MCALL field is supposed to be infinite? For XBTUSD the MCALL field is supposed to have some value.

**Comment by evgrmn** [comment]
Bitmex has stopped sending these values from the websocket only when the position value changes. Added loading of initial values from the /api/v1/position endpoint.

**Comment by nikolayromenskiy** [comment]
PNL still has the wrong dimension.

**Comment by evgrmn** [comment]
Solved. See issue #187
