### ISSUE TITLE
Bybit BTCUSDT: empty value for the field MCALL

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#179]
![Screenshot from 2024-04-26 14-39-23](https://github.com/evgrmn/tmatic/assets/148801289/1a823ddf-fac7-430e-a243-d0061b028356)

When Tmatic is initially loaded the field shows value 'inf', but after some time of running the value disappears.

**Comment by evgrmn** [comment]
According to the documentation, Bybit sends "" when liqPrice <= minPrice or liqPrice >= maxPrice. I changed "" to "inf" so that the field is not empty.
