### ISSUE TITLE
Suggestion for: api/bitmex/ws.py > def __update_position()

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#187]
if "currentQty" in values:
            instrument.currentQty = values["currentQty"]
            self.positions[symbol]["POS"] = instrument.currentQty
        if instrument.currentQty == 0:
            instrument.avgEntryPrice = 0
            instrument.marginCallPrice = 0
            instrument.unrealisedPnl = 0
        else:
            if "avgEntryPrice" in values:
                instrument.avgEntryPrice = values["avgEntryPrice"]
            if "unrealisedPnl" in values:
                instrument.unrealisedPnl = values["unrealisedPnl"]
            if "marginCallPrice" in values:
                if values["marginCallPrice"] == 100000000:
                    instrument.marginCallPrice = "inf"
                else:
                    instrument.marginCallPrice = values["marginCallPrice"]

**Comment by evgrmn** [comment]
Additionally put unrealisedPnl in right dimension.
                instrument.unrealisedPnl = (
                    values["unrealisedPnl"]
                    / self.currency_divisor[instrument.settlCurrency[0]]
                )
I entered this code into the program.
