### ISSUE TITLE
No positions at Bybit BTCUSD but MCALL shows 'inf'

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#188]
![Screenshot from 2024-04-27 18-13-21](https://github.com/evgrmn/tmatic/assets/148801289/b8c4fef4-4272-477b-84f8-132889f602e3)

**Comment by evgrmn** [comment]
Fixed: MCALL = "inf" only if "liqPrice" = "" and Instrument.currentQty is not 0.
