### ISSUE TITLE
Python stopped unexpectedly error

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#193]
The error is a result of 'os.abort()' code action. 

![Screenshot from 2024-05-07 16-53-23](https://github.com/evgrmn/tmatic/assets/148801289/9a929281-1dc2-44f0-abfb-e6c0135ea242)

**Comment by evgrmn** [comment]
Temporarily commented out the lines where abort() is located.

**Comment by evgrmn** [comment]
It's possible that os.abort() was forgotten to be cleared during debugging. Please report if this error occurs again.
