### ISSUE TITLE
Account table

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#272]
1. Turn refresh of the table off when switch between exchanges.

2. Check width alignment for the first column of the Account table. Wrong behavior.

**Comment by evgrmn** [comment]
Point 1. Corrected in commit 24a814f.
Point 2. Please describe the problem in detail. I don't see any wrong behavior.

**Comment by evgrmn** [comment]
Point 2 fixed in commit 7ec89d2.
