### ISSUE TITLE
Misprints in strategy.py

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#286]
# def strategy():                                                             
#   if kline("bid", -1) > kline("bid", -10)                                   
#       instrument.buy(bot=bot, move=True, cancel=True)                       
#   else:                                                                     
#       insrument.sell(bot=bot, move=True, cancel=True)

1) No ":" after if kline("bid", -1) > kline("bid", -10) 
2) "insrument" instead of "instrument" in the row insrument.sell(bot=bot, move=True, cancel=True)

**Comment by evgrmn** [comment]
Fixed in the commit 8e4d11b.
