### ISSUE TITLE
IndexError: tuple index out of range

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#291]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\solot\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\solot\Documents\240822_2\functions.py", line 1819, in handler_bot
    iid = tree.selection()[0]
          ~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range

**Comment by nikolayromenskiy** [comment]
This error occurred again when I clicked "Delete" in the Bot menu. Bot deleted and at the same time I got the error.

**Comment by nikolayromenskiy** [comment]
How to cause this error:

1) Add a new bot.
2) Close Tmatic.
3) Open Tmatic.
4) Go to Bot Menu and Delete the new-created bot.

**Comment by evgrmn** [comment]
Fixed in commit 370fdab.
