### ISSUE TITLE
The strategy.py is probably not being updated

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#296]
Initially I had the following:

from tools import Bitmex, Bybit, Bot
bot = Bot()                                                                 
instrument = Bitmex["XBTUSDT"]

Then I removed Bitmex and clicked "Update strategy":

from tools import Bybit, Bot
bot = Bot()                                                                 
instrument = Bitmex["XBTUSDT"]

As a result the strategy showed no errors and continued to make orders. Then I rebooted Tmatic, and, at last, the NameError occurred: name 'Bitmex' is not defined.

**Comment by evgrmn** [comment]
Fixed in commit 16346b9.
