### ISSUE TITLE
No possibility to change strategy.py when error and at the same time a bot is Active

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#297]
I have a nameError for some bot. At the same time the bot has state "Active". To improve the error I have to edit the bot's strategy.py file. But it is impossible because this editing is prohibited while bots' state is "Active". So, I proceed to "State" in order to suspend, but no button "Suspend", only error message displayed.

To solve the problem we have to leave a possibility to suspend bot even any error is on. If bot is already suspended an some error is on, then still no activation possible.

**Comment by evgrmn** [comment]
Fixed in commit 313d43f.
