### ISSUE TITLE
No expected position for bot

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#298]
I start Tmatic with only Bitmex enabled. The following error occurred:

10:40:48.571  test_bot_3 bot has open position on ('BTCUSDT', 'Bybit'), but Bybit is not enabled. Position on ('BTCUSDT', 'Bybit') ignored. Add Bybit to the .env file.

I add Bybit to .env - no errors at loading as a result. Then I go to the bot's menu to see its positions, but I do not see any positions expected.

**Comment by nikolayromenskiy** [comment]
According to the database data (see below) the balance for test_bot_3 is 0. But the balance for ('BTCUSDT', 'Bybit') is really not 0, because of this trade: 8b5f55e5-730b-5b7f-837e-ae632d5412ff where EMI is 'BTCUSDT' and REFER is 'test_bot_3'. So, the problem is that Tmatic during loading process erroneously considers 8b5f55e5-730b-5b7f-837e-ae632d5412ff trade is made by test_bot_3, that is wrong.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><body>
 EXECID | EMI | REFER | MARKET | CURRENCY | SYMBOL | SIDE | QTY | TRADE_PRICE
-- | -- | -- | -- | -- | -- | -- | -- | --
4b4b45c6-6209-5185-b7dd-8f859bffc3db | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Buy | 0.001 | 59541.2
8b5f55e5-730b-5b7f-837e-ae632d5412ff | BTCUSDT | test_bot_3 | Bybit | USDT | BTCUSDT | Sell | -0.001 | 59521.2
d5fe90b4-3103-5c61-b4a1-57bed05a9496 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Sell | -0.001 | 59052.5
d3b8cabe-2ac6-5016-8d69-d0c8b560187a | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Sell | -0.001 | 59009.6
e5da8f2d-2c4f-55d3-8ba3-bcdbba003f89 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Buy | 0.001 | 59585.3
67a0d2e1-f1fe-5a6a-9478-eda7592960c3 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Buy | 0.001 | 59531.2
5988772d-5efa-5c85-843e-c2b8c52d5f51 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Sell | -0.001 | 59430.3
5031b798-4a44-5ceb-b798-cb5e1546f8b0 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Sell | -0.001 | 59430.3
bff5d7f0-a035-56d9-8f94-524805949426 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Buy | 0.001 | 59575.3
aa79eb59-2ddb-56be-8716-885d322b36f2 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Buy | 0.001 | 59430.3
aac7beb0-a0af-50b4-8e28-8ce32df3db55 | test_bot_3 | test_bot_3 | Bybit | USDT | BTCUSDT | Sell | -0.001 | 59375

</body></html>

**Comment by evgrmn** [comment]
I slightly reworked the SQL query in botinit/init.py. I think it works fine now. See commit 77813eb.

**Comment by nikolayromenskiy** [comment]
This amendment is incorrect because making "where pos <> 0" clears the "Results" table when no position at the moment. Make the following construction instead:

if value["MARKET"] in var.market_list:
     ws = Markets[value["MARKET"]]
     instrument = ws.Instrument[symbol]
     ..........
     ..........
     ..........
elif value["POS"] != 0:
     message = (
          name
     ..........
     ..........
     ..........

**Comment by evgrmn** [comment]
I think this will work. See commit 9b3d1b3.
