### ISSUE TITLE
The hint "You are probably trying to use an exchange that is not connected" for this type of error is irrelevant

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#303]
ValueError: The instrument ('XBTUSD', 'Bybit') not found.

You are probably trying to use an exchange that is not connected. You should either add the exchange in the .env file or correct the strategy file or delete ``test_bot`` using the ``Bot Menu``.

**Comment by evgrmn** [comment]
Removed ValueError and AttributeError handling in import_bot_module function. See commit 602304a.
