### ISSUE TITLE
Please check the commission value for the Fund rows. Are fund rows applicable for BTC-26JUL24 futures contract?

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#307]
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"><html><head><body>
EXECID | EMI | MARKET | CURRENCY | SIDE | QTY | PRICE | COMMISS | TTIME
-- | -- | -- | -- | -- | -- | -- | -- | --
1721894403130580_BTC | BTC-26JUL24 | Deribit | BTC | Fund | 10 | 63936.07 | 0 | 2024-07-25 08:00:00.035000+00:00
190767462_BTC | BTC-26JUL24 | Deribit | BTC | Buy | 10 | 67500 | 0 | 2024-07-21 10:58:28.412000+00:00
1721635203351092_BTC | BTC-26JUL24 | Deribit | BTC | Fund | 10 | 65895.12 | 0 | 2024-07-22 08:00:00.032000+00:00
1721721603158157_BTC | BTC-26JUL24 | Deribit | BTC | Fund | 10 | 66567.49 | 0 | 2024-07-23 08:00:00.032000+00:00
1721808003417367_BTC | BTC-26JUL24 | Deribit | BTC | Fund | 10 | 65796.81 | 0 | 2024-07-24 08:00:00.033000+00:00
1721980803334379_BTC | BTC-26JUL24 | Deribit | BTC | Sell | -10 | 66996.24 | 0 | 2024-07-26 08:00:00.032000+00:00

</body></html>

**Comment by evgrmn** [comment]
These entries do not actually affect any calculations in the application. In any case, they are now excluded when loading the trade history. See commit 53bd406.
