### ISSUE TITLE
530 error in Bitmex

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#325]
2024-09-11 09:58:53,865 - root - INFO - 

hello

2024-09-11 09:58:54,426 - api.api - INFO - Bitmex - Requesting all active instruments.
___________try_response
530 Server Error:  for url: https://testnet.bitmex.com/api/v1/instrument/active
-----
{'response': <Response [530]>, 'request': <PreparedRequest [GET]>}
-----
<Response [530]>
-----
{'_content': b'<!DOCTYPE html>\n\n\n\n <html class="no-js" lang="en-US"> \n<head>\n<title>Origin DNS error | testnet.bitmex.com | Cloudflare</title>\n<meta charset="UTF-8" />\n<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\n<meta http-equiv="X-UA-Compatible" content="IE=Edge" />\n<meta name="robots" content="noindex, nofollow" />\n<meta name="viewport" content="width=device-width,initial-scale=1" />\n<link rel="stylesheet" id="cf_styles-css" href="/cdn-cgi/styles/main.css" />\n\n\n<script>\n(function(){if(document.addEventListener&&window.XMLHttpRequest&&JSON&&JSON.stringify){var e=function(a){var c=document.getElementById("error-feedback-survey"),d=document.getElementById("error-feedback-success"),b=new XMLHttpRequest;a={event:"feedback clicked",properties:{errorCode:1016,helpful:a,version:1}};b.open("POST","https://sparrow.cloudflare.com/api/v1/event");b.setRequestHeader("Content-Type","application/json");b.setRequestHeader("Sparrow-Source-Key","c771f0e4b54944bebf4261d44bd79a1e");\nb.send(JSON.stringify(a));c.classList.add("feedback-hidden");d.classList.remove("feedback-hidden")};document.addEventListener("DOMContentLoaded",function(){var a=document.getElementById("error-feedback"),c=document.getElementById("feedback-button-yes"),d=document.getElementById("feedback-button-no");"classList"in a&&(a.classList.remove("feedback-hidden"),c.addEventListener("click",function(){e(!0)}),d.addEventListener("click",function(){e(!1)}))})}})();\n</script>\n\n<script defer src="https://performance.radar.cloudflare.com/beacon.js"></script>\n</head>\n<body>\n  <div id="cf-wrapper">\n    <div class="cf-alert cf-alert-error cf-cookie-error hidden" id="cookie-alert" data-translate="enable_cookies">Please enable cookies.</div>\n    <div id="cf-error-details" class="p-0">\n      <header class="mx-auto pt-10 lg:pt-6 lg:px-8 w-240 lg:w-full mb-15 antialiased">\n         <h1 class="inline-block md:block mr-2 md:mb-2 font-light text-60 md:text-3xl text-black-dark leading-tight">\n           <span data-translate="error">Error</span>\n           <span>1016</span>\n         </h1>\n         <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">Ray ID: 8c16cd4f1bf45432 &bull;</span>\n         <span class="inline-block md:block heading-ray-id font-mono text-15 lg:text-sm lg:leading-relaxed">2024-09-11 09:58:54 UTC</span>\n        <h2 class="text-gray-600 leading-1.3 text-3xl lg:text-2xl font-light">Origin DNS error</h2>\n      </header>\n\n      <section class="w-240 lg:w-full mx-auto mb-8 lg:px-8">\n          <div id="what-happened-section" class="w-1/2 md:w-full">\n            <h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_happened">What happened?</h2>\n            <p>You\'ve requested a page on a website (testnet.bitmex.com) that is on the <a href="https://www.cloudflare.com/5xx-error-landing/" target="_blank">Cloudflare</a> network. Cloudflare is currently unable to resolve your requested domain (testnet.bitmex.com).\n            \n          </div>\n\n          \n          <div id="resolution-copy-section" class="w-1/2 mt-6 text-15 leading-normal">\n            <h2 class="text-3xl leading-tight font-normal mb-4 text-black-dark antialiased" data-translate="what_can_i_do">What can I do?</h2>\n            <p><strong>If you are a visitor of this website:</strong><br />Please try again in a few minutes.</p><p><strong>If you are the owner of this website:</strong><br />Check your DNS settings. If you are using a CNAME origin record, make sure it is valid and resolvable. <a rel="noopener noreferrer" href="https://support.cloudflare.com/hc/en-us/articles/234979888-Error-1016-Origin-DNS-error">Additional troubleshooting information here.</a></p>\n          </div>\n          \n      </section>\n\n      <div class="feedback-hidden py-8 text-center" id="error-feedback">\n    <div id="error-feedback-survey" class="footer-line-wrapper">\n        Was this page helpful?\n        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-yes" type="button">Yes</button>\n        <button class="border border-solid bg-white cf-button cursor-pointer ml-4 px-4 py-2 rounded" id="feedback-button-no" type="button">No</button>\n    </div>\n    <div class="feedback-success feedback-hidden" id="error-feedback-success">\n        Thank you for your feedback!\n    </div>\n</div>\n\n\n      <div class="cf-error-footer cf-wrapper w-240 lg:w-full py-10 sm:py-4 sm:px-8 mx-auto text-center sm:text-left border-solid border-0 border-t border-gray-300">\n  <p class="text-13">\n    <span class="cf-footer-item sm:block sm:mb-1">Cloudflare Ray ID: <strong class="font-semibold">8c16cd4f1bf45432</strong></span>\n    <span class="cf-footer-separator sm:hidden">&bull;</span>\n    <span id="cf-footer-item-ip" class="cf-footer-item hidden sm:block sm:mb-1">\n      Your IP:\n      <button type="button" id="cf-footer-ip-reveal" class="cf-footer-ip-reveal-btn">Click to reveal</button>\n      <span class="hidden" id="cf-footer-ip">31.24.63.29</span>\n      <span class="cf-footer-separator sm:hidden">&bull;</span>\n    </span>\n    <span class="cf-footer-item sm:block sm:mb-1"><span>Performance &amp; security by</span> <a rel="noopener noreferrer" href="https://www.cloudflare.com/5xx-error-landing" id="brand_link" target="_blank">Cloudflare</a></span>\n    \n  </p>\n  <script>(function(){function d(){var b=a.getElementById("cf-footer-item-ip"),c=a.getElementById("cf-footer-ip-reveal");b&&"classList"in b&&(b.classList.remove("hidden"),c.addEventListener("click",function(){c.classList.add("hidden");a.getElementById("cf-footer-ip").classList.remove("hidden")}))}var a=document;document.addEventListener&&a.addEventListener("DOMContentLoaded",d)})();</script>\n</div>\n\n\n    </div>\n  </div>\n\n  <script>\n  window._cf_translation = {};\n  \n  \n</script>\n\n</body>\n</html>\n', '_content_consumed': True, '_next': None, 'status_code': 530, 'headers': {'Date': 'Wed, 11 Sep 2024 09:58:54 GMT', 'Content-Type': 'text/html; charset=UTF-8', 'Content-Length': '6203', 'Connection': 'keep-alive', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'same-origin', 'Cache-Control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0', 'Expires': 'Thu, 01 Jan 1970 00:00:01 GMT', 'Server': 'cloudflare', 'CF-RAY': '8c16cd4f1bf45432-TLL', 'alt-svc': 'h3=":443"; ma=86400'}, 'raw': <urllib3.response.HTTPResponse object at 0x7a52dd35d840>, 'url': 'https://testnet.bitmex.com/api/v1/instrument/active', 'encoding': 'UTF-8', 'history': [], 'reason': '', 'cookies': <RequestsCookieJar[]>, 'elapsed': datetime.timedelta(microseconds=204502), 'request': <PreparedRequest [GET]>, 'connection': <requests.adapters.HTTPAdapter object at 0x7a52dd35c9a0>}
-----
Traceback (most recent call last):
  File "/home/rmn/240910_2/api/http.py", line 90, in request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 530 Server Error:  for url: https://testnet.bitmex.com/api/v1/instrument/active

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmn/240910_2/api/errors.py", line 173, in try_response
    response["error"]["code"]
TypeError: 'Response' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rmn/240910_2/api/api.py", line 70, in start_ws
    if WS.get_active_instruments(self):
  File "/home/rmn/240910_2/api/api.py", line 140, in get_active_instruments
    return Agents[self.name].value.get_active_instruments(self)
  File "/home/rmn/240910_2/api/bitmex/agent.py", line 17, in get_active_instruments
    data = Send.request(self, path=Listing.GET_ACTIVE_INSTRUMENTS, verb="GET")
  File "/home/rmn/240910_2/api/http.py", line 94, in request
    status = Error.handler(
  File "/home/rmn/240910_2/api/errors.py", line 92, in handler
    response = try_response(response, exception)
  File "/home/rmn/240910_2/api/errors.py", line 204, in try_response
    print(response["error"])
TypeError: 'Response' object is not subscriptable

2024-09-11 09:58:54,638 - api.api - ERROR - Bitmex Instruments not loaded. Reboot.
2024-09-11 09:58:56,641 - connect - INFO - 

2024-09-11 09:58:56,641 - connect - INFO - Something went wrong while loading Bitmex. Reboot.

**Comment by evgrmn** [comment]
This issue was resolved in one of the latest commits.
