### ISSUE TITLE
In some cases the newly subscribed symbol doesn't show up it the Instruments' table

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#347]
If Instruments' table currently displays Bybit's symbols and I am trying to subscribe to one of the Bitmex symbol (XBTM25 in this example), then in this case the Bybit part properly closes, the Bitmex opens, but the newly subscribed Bitmex symbol does not show up. Eventually it could be got displayed if I switch from Bitmex to Bybit and again to Bitmex.
![Screenshot from 2024-09-25 19-29-54](https://github.com/user-attachments/assets/a180ec94-e641-44b9-8edb-5dbe9a33225b)

**Comment by evgrmn** [comment]
Fixed in commit 4ff50b9.
