### ISSUE TITLE
Error in the instruments' table after rebooting

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#349]
After F3 when I switch between the markets in the instruments' table the cursor line erroneously lands on the wrong row (see the screenshot). This situation leads to the following error:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/functions.py", line 2005, in handler_instrument
    TreeTable.instrument.on_rollup(iid=items[0], setup="child")
  File "/home/display/variables.py", line 1136, in on_rollup
    iid = self.children_hierarchical[parent][0]
IndexError: tuple index out of range

![Screenshot from 2024-09-25 23-28-10](https://github.com/user-attachments/assets/5d8ad033-a2d8-461b-ad9b-2cc1b511ea76)

**Comment by evgrmn** [comment]
Fixed in commit 63b70aa
