### ISSUE TITLE
Trying to subscribe to already subscribed symbol

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#354]
When I am trying to subscribe to already subscribed symbol, then the appropriate pop-up window shows up. This is correct. At the same time nothing happens with the Instrument's table and the Orderbook table. I think, that the Instrument table must select the symbol I am trying to subscribe and the Orderbook table must be switched to the symbol.

**Comment by evgrmn** [comment]
Solved in commit 626af34.
