### ISSUE TITLE
The Option Desk improper pop-up

### ISSUE THREAD

**Issue by nikolayromenskiy** [evgrmn/tmatic#379]
When I unsubscribe from a symbol and the next symbol is an option, then the Option Desk is displayed which shouldn't have been. I propose to pop up the Option Desk automatically only after the subscription made. Otherwise it should be popped up only after user's click (double-click if the strike already selected).

**Comment by evgrmn** [comment]
Fixed in commit 0c011ac.

**Comment by nikolayromenskiy** [comment]
The problem still persists. I subscribe to an option, then automatically opens the Option Chain window with the default selection for the first Call-strike. So, if I close the Option Chain window without user's selection, then the improper pop-up problem still persists.

**Comment by evgrmn** [comment]
Fixed in commit 09ae6bc.
